### ISSUE TITLE
Interaction between flow and `java.lang.Error`

### ISSUE THREAD

**Issue by IGJoshua** [fmnoise/flow#6]
The class `java.lang.Error` from the JDK is a subclass of `Throwable` which is intended specifically to not be caught by "reasonable applications". From [the javadoc](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Error.html):
> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions. The ThreadDeath error, though a "normal" condition, is also a subclass of Error because most applications should not try to catch it.

I'm not taking a stance on this, but I'd like to open discussion on whether or not this library should add a default implementation of `fmnoise.flow/Caught` for `java.lang.Error` that will re-throw the object without further processing.

As noted by the above quote from the javadoc, there are conditions which are normal in the JVM which subclass from `Error` which are explicitly designed to not be caught by most user code.

As an example of other effects this can have, my library [farolero](https://github.com/IGJoshua/farolero) creates a class `Signal` which derived from `Error`, with the intention that it will not be caught by any other library, and is used as a generalized stack unwinding tool.

I personally am of two minds for this:

On the one hand, making this change *will* break some existing callers if this library sees any significant use, as e.g. assertion errors are in fact `Error`s, and may be intended to be caught by most existing users. Besides this I'm not aware of any other `Error`s which would often be intended to be caught by end users, which gives a possible mitigation to give a further protocol implementation for `AssertionError` which does permit the value to be caught.

On the other hand, if we don't make this change, then any library which makes use of `Error` for its ability to not be caught by most code, whether to construct new control flow mechanisms like farolero, or to crash a thread responsibly in the case of corrupted usage of a native library, then any user who uses these libraries must be conscious of this fact and add their own extensions, or it forces the library developers to be aware of flow and to add a protocol implementation in their libraries in an optional way, which can be difficult, and sometimes (e.g. in cljs) impossible to do transparently.

I'd like to hear what others think about this.

**Comment by fmnoise** [comment]
I'd leave that decision for library consumers. Really not sure if dictating any good practice makes sense here as all configuration possibilities are provided.
