### ISSUE TITLE
More uniform example in README

### ISSUE THREAD

**Issue by onetom** [fmnoise/flow#8]
It took awhile to understand why the 1st example in the README has these irregularities between the steps:
```clojure
  (->> (check-user req)
       (then (fn [_] (check-entity-id req)))
       (then #(check-entity-exists db %))
```

With a slight reformulation of how we think about the steps, we can construct a more uniform processing pipeline:
```clojure
(defn when-it-has-user [req]
  (if (:user req)
    req
    (ex-info "Login requred" {:code 401})))

(defn when-it-has-entity-id [req]
  (if (:id req)
    req
    (ex-info "Missing entity id" {:code 400})))

(defn existing-entity [db id]
  (or (fetch-entity db id)
      (ex-info "Entity not found" {:code 404})))

(defn accessible-entity [entity user]
  (if (accessible? entity user)
    entity
    (ex-info "Access denied" {:code 403})))

(defn update-handler [req db]
  (->> req
       (then when-it-has-user)
       (then when-it-has-entity-id)
       (then #(existing-entity db %))
       (then #(accessible-entity % (:user req)))
       (then #(update-entity! % (:params req)))
       (else format-error)))
```

the parentheses are also off in the current example. i guess, should have been:
```clojure
(defn update-handler [req db]
  (->> (check-user req)
       (then (fn [_] (check-entity-id req)))
       (then #(check-entity-exists db %))
       (then #(check-entity-access % (:user req)))
       (then #(update-entity! % (:params req)))
       (else format-error)))
```

This also highlights a pattern, which is similar to using `assert`, but it's also similar to `update` and `swap!`, in case the predicate function has extra arguments.

I envision something like:
```clojure
(defn update-handler [req db]
  (->> req
       (assert (ex-info "Login required" {:code 401})
               :user)
       (assert (ex-info "Missing entity id" {:code 400})
               :id)
       (then->> (existing-entity db))
       (assert (ex-info "Entity not found" {:code 404})
               accessible? (:user req))
       (then-> (update-entity! (:params req)))
       (else format-error)))
```
but the threading is not correct of course; it would need more thought to straighten it out.
(`(ex-info "Login requred" {:code 401})))` has a typo; it should be `required`)

of course, this would lead to introducing even more primitives, like `then->>` and `then->`, but that might be avoidable, if we define `then`, `else`, etc to be thread-first-compatible, which would allow intermixing `->>` and `as->` forms, like so:

```clojure
(-> some-single-value
    (update ,,,)
    (assoc ,,,)

    (as-> xxx 
          (funky-function ,,, xxx ,,,))

    (derive-some-collection-from-it ,,,)

    (->> (filter ,,,)
         (map ,,,)
         (into {}))

    (process-as-a-single-value-again ,,,)
    (dissoc ,,,)
    ,,,)
```

so the README could look like this:
```clojure
(defn update-handler [req db]
  (-> req
      (assert (ex-info "Login required" {:code 401})
              :user)
      (assert (ex-info "Missing entity id" {:code 400})
              :id)
      (then (->> (existing-entity db)))
      (assert (ex-info "Entity not found" {:code 404})
              accessible? (:user req))
      (then update-entity! (:params req))
      (else format-error)))
```

**Comment by fmnoise** [comment]
@onetom thank you for the feedback 👍🏽 

> we can construct a more uniform processing pipeline

```clj 
(->> req (then when-it-has-user) ...
```
☝🏽 We can use it just to make it look nicer, but practically if `req` is known to be not a `Throwable`, using `then` is redundant. I wanted it to be practical first, so it  also demonstrates variety of checks in different scenarios
eg
```clj
(then (fn [_] (check-entity-id req)))
```
☝🏽 Here we don't really care about "successful" result of previous check because  we can check against initial `ref`. Using previous result may give false feeling that `ref` was changed during previous check, that's why I usually explicitly use `(fn [_] ...)` to indicate that.

>  if we define then, else, etc to be thread-first-compatible

We also have `?ok` and `?err` which accepts value as first argument so it can be used (and I use it sometimes) when `->` is preferred

Honestly the whole initial example is not how I'm writing code nowadays, I always use `flet` for that

**Comment by fmnoise** [comment]
probably readme needs more info about `?err`, `?ok` and `?throw` 🤔

**Comment by fmnoise** [comment]
> the parentheses are also off in the current example

my bad, fixed now, thanks  👍🏽

**Comment by fmnoise** [comment]
> which is similar to using assert
```clj
(assert (ex-info "Login required" {:code 401}) :user)
```
I'm not sure I understood this example, can `assert` do this?
Also `assert` relies on dynamic var, which may create some surprises in production usage

**Comment by onetom** [comment]
The example in question definitely demonstrates a lot of scenarios, but without your comments I was not sure what to make of it, so thanks for the explanations!

Having some `flow/assert` construct would make it explicit that you are not transforming the value, only for the sake of testing. i realized that it probably reads cleaner if the exception comes last:

```clojure
(defn update-handler [req db]
  (-> req
      (assert :user
              (ex-info "Login required" {:code 401}))
      (assert :id
              (ex-info "Missing entity id" {:code 400}))
      (then (->> (existing-entity db)))
      (assert accessible? (:user req)
              (ex-info "Entity not found" {:code 404}))
      (then update-entity! (:params req))
      (else format-error)))
```
and i guess the implementation of that `assert` might be:
```clojure
(defn assert
  "Returns value, if `(pred value ...)` is truthy, or the last argument,
   which is supposed to be a `flow/?err`"
  [value pred & etc]
  (let [pred-args (butlast etc)
        err (last etc)]
    (if (apply pred value pred-args)
      value
      err)))
```

This way, existing, *pure* predicate functions can be used as-is, no need to create an anonymous *closure* (providing `req`).

> probably readme needs more info about `?err`, `?ok` and `?throw` 🤔

Some usage example would be definitely welcome, because even skimming through the tests didn't quite give me an intuition of how to use these functions, or whether are they even intended to be used directly, or only through the higher-level functions.

> I'm not sure I understood this example, can assert do this?

no, `clojure.core/assert` can't do this. i was hinting at some imaginary `flow/assert`. didn't have a better idea for a name at that time.

I will study the code and the tests more, just wanted to share my initial impressions, which can only be experienced once :)
I'm new to this style of programming, so sorry, if I'm proposing silly approaches.

**Comment by fmnoise** [comment]
Thank you for suggestions! 
`flow/assert` use-case looks good, but `cond` usually works just fine for that 🙂 

my real production `flow` code is 99% something like this
```clj
(defn refund-payment
  [{:keys [payment-id amount items]}]
  (->> (flet [payment (or (find-payment payment-id)
                          (ex-info "Payment not found" {:id payment-id}))
              _ (cond
                  (and amount (seq items))
                  (ex-info "Only total amount or returned items can be supplied" {:items items :amount amount})

                  (some (comp nil? :line-item/product) items)
                  (ex-info "Incorrect product supplied" {:items items})

                  (and (seq items) (->> items (map :line-item/product) (apply distinct?) not))
                  (ex-info "Items should be grouped by product" {:items items}))]
         (api/perform-refund! payment amount items))
       (else respond-with-error)))
```

**Comment by onetom** [comment]
I just saw this lib on Hacker News: https://grishaev.me/en/pact/
Looks quite similar to this lib, but it's using a thread-first API.
Just putting it here, to encourage idea cross-pollination.
