### ISSUE TITLE
Illustration attribution

### ISSUE THREAD

**Issue by onetom** [fmnoise/flow#9]
Where did you get the https://raw.githubusercontent.com/fmnoise/flow/master/doc/flow.png from?

It looks like one of Scott Wlaschin's drawings - whom you did attribute -, but it would be nice to pin-point the source of that specific image too.

I'm curious, because I'd like to understand how prevalent are those function names.

**Comment by fmnoise** [comment]
@onetom I created that drawing by myself using 
https://app.diagrams.net/

**Comment by onetom** [comment]
> @onetom I created that drawing by myself using https://app.diagrams.net/

very fancy looking diagram!
i used this tool the last time, when it was still called draw.io.
nowadays i just draw sketches with https://excalidraw.com/
